import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "../styles/globals.scss";
import Header from "./components/layout/Header";

const inter = Inter({ subsets: ["latin"], display: "swap" });
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <div className="h-screen flex flex-col justify-between bg-rose-950">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
