import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "../styles/globals.scss";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"], display: "swap" });
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Create Next App YEDEK",
    template: "%s | Code Generation",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <div className="min-h-screen flex flex-col justify-start items-stretch bg-white dark:bg-black">
          <Header />
          <main className="container mx-auto py-5 bg-gray-900 min-h-lvh">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
